"""Generate MCPGuard-compatible YAML policies from compliance results."""

from __future__ import annotations

from pathlib import Path
from typing import Any

MCPGUARD_POLICY_TEMPLATE = """# MCPGuard Policy — Auto-generated by AgentForensics
# Generated: {timestamp}
# Framework: {framework}

mode: http
listen_host: 127.0.0.1
listen_port: 8080
target_url: {target_url}

rate_limit: {rate_limit}
rate_window: 60

block_on_injection: true
block_on_poisoning: true

allow:
{allow_list}

deny:
{deny_list}
"""


def generate_mcpguard_policy(
    compliance: dict[str, Any],
    target_url: str = "http://localhost:8000",
    rate_limit: int = 100,
) -> str:
    """Generate an MCPGuard-compatible YAML policy from compliance results.

    Analyzes compliance check results to build allow/deny lists for MCPGuard
    based on detected policy violations, blocked actions, and risk levels.

    Args:
        compliance: Compliance check results from ``engine.check_compliance()``.
        target_url: Target MCP server URL.
        rate_limit: Max requests per rate window.

    Returns:
        YAML policy string suitable for MCPGuard.
    """
    blocked_tools = _get_blocked_tools(compliance)
    detected_anomalies = _has_anomalies(compliance)

    if detected_anomalies:
        for dangerous in ("exec", "shell", "sudo", "curl", "wget", "sql"):
            blocked_tools.add(dangerous)

    allow_tools = {
        "read_file",
        "get_weather",
        "search_web",
        "get_time",
        "calculate",
        "translate",
        "summarize",
        "list_directory",
    }
    allow_tools -= blocked_tools

    allow_list = "\n".join(f"  - {tool}" for tool in sorted(allow_tools))
    deny_list = "\n".join(f"  - {tool}" for tool in sorted(blocked_tools))

    adj_rate = _adjusted_rate_limit(compliance, rate_limit)

    return MCPGUARD_POLICY_TEMPLATE.format(
        timestamp=compliance.get("timestamp", ""),
        framework=compliance.get("framework", "nist_ai_rmf"),
        target_url=target_url,
        rate_limit=adj_rate,
        allow_list=allow_list if allow_list else "  # No safe tools identified",
        deny_list=deny_list if deny_list else "  # No tools denied",
    )


def save_mcpguard_policy(
    compliance: dict[str, Any],
    output_path: str | Path,
    target_url: str = "http://localhost:8000",
    rate_limit: int = 100,
) -> Path:
    """Generate and save an MCPGuard policy to file.

    Args:
        compliance: Compliance check results.
        output_path: Path to save the policy YAML.
        target_url: Target MCP server URL.
        rate_limit: Max requests per rate window.

    Returns:
        Path to the saved policy file.
    """
    policy = generate_mcpguard_policy(compliance, target_url, rate_limit)
    path = Path(output_path)
    path.write_text(policy)
    return path


def _get_blocked_tools(compliance: dict[str, Any]) -> set[str]:
    """Extract blocked tools from compliance check details."""
    blocked: set[str] = set()
    tools = {
        "write_file",
        "http_request",
        "execute_command",
        "delete_file",
        "network_scan",
        "sql_query",
        "modify_system",
    }
    for check in compliance.get("checks", []):
        detail = (check.get("details") or "").lower()
        for tool in tools:
            if tool in detail:
                blocked.add(tool)
    return blocked


def _has_anomalies(compliance: dict[str, Any]) -> bool:
    """Check if compliance results indicate anomalous activity."""
    for check in compliance.get("checks", []):
        if "anomal" in (check.get("details") or "").lower():
            return True
    failed = compliance.get("failed", 0)
    return bool(failed > 3) if isinstance(failed, int) else False


def _adjusted_rate_limit(compliance: dict[str, Any], default: int = 100) -> int:
    """Reduce rate limit if compliance has many failures."""
    failed = compliance.get("failed", 0)
    if failed >= 5:
        return max(10, default // 5)
    if failed >= 3:
        return max(30, default // 3)
    return default
